FROM python:alpine3.18
# FROM node:current-alpine3.18

# https://npmmirror.com/mirrors/node/v18.16.1/node-v18.16.1-linux-x64.tar.xz
# https://npmmirror.com/mirrors/node/v20.4.0/node-v20.4.0-linux-x64.tar.xz

# COPY --from=python_stage /path/to/files /destination/path